### ISSUE TITLE
MBO tree

### ISSUE THREAD

**Issue by marionf** [PrestaShop/ps_mbo#32] opened 2018-08-30 14:35 UTC
With MBO, I have the following tree :
Module catalog > Modules selections (when I click on Module catalog, the Modules selections tab isn't selected, don't know if it's the wanted behavior ?)
Modules Manager > Modules
Modules Manager > Module catalog
Modules Manager > Alerts
Modules Manager > Updates

Without I have this :
Module Catalog > Module Catalog
Module Catalog > Modules Selections (addons iframe)
Module Manager > Modules
Module Manager > Alerts
Modules Manager > Updates

https://drive.google.com/file/d/1xC_OaPNirthXkFgCTCkUNRenCz5C7NMo/view?usp=sharing

I think I should have the same tree as in the core with MBO ? 
@LouToma can you confirm that ?

**Comment by LouToma** [comment] 2018-08-30 15:01
With MBO, I have the following tree :
Module Catalog > Module Catalog
Module Catalog > Module Selections 
Module Manager > Modules
Module Manager > Alerts
Module Manager > Updates

We should get exactly the same thing with and without MBO.
Also, when I click on Module Catalog, the first tab "Module Catalog" must be selected automatically.

Be careful with the "s", its "Module Selections" and not "Modules Selections" in the 2nd tab.

**Comment by mbadrani** [comment] 2018-09-13 14:31
I've checked it, with MBO installed, the first tab (in Module Catalog) is still not selected (it should by default when we access on this category)
...And "Modules Selections" still contain "s" but it the same without MBO

**Comment by Quetzacoalt91** [comment] 2018-09-13 16:01
The issue is actually a wrong link in the side menu. Fixed in the core with https://github.com/PrestaShop/PrestaShop/pull/10427.

**Closed** 2018-09-14 13:43 UTC
Labels: QA approved, bug
